package com.eci.anaplan.flight.idr.aggregations.joiners

import org.apache.spark.sql.{DataFrame, SparkSession}

import javax.inject.{Inject, Singleton}

@Singleton
class FlFinalJoiner @Inject()(spark: SparkSession, flMultiplierJoiner: FlMultiplierJoiner) {

  import spark.implicits._

  private def joinDataFrames: DataFrame = {
    
    val FinalTransform = flMultiplierJoiner.get()

    FinalTransform
      .select(
        $"booking_issue_date_formated".as("booking_issue_date"),
        $"locale",
        $"product_type",
        $"business_model",
        $"booking_id",
        $"fulfillment_id",
        $"airline_id",
        $"brand_codes",
        $"provider_pnr",
        $"airline_pnr",
        $"departure_date",
        $"non_refundable_date",
        $"contract_entity",
        $"trip_type",
        $"route",
        $"airport_countries",
        $"destination_airport_country_name",
        $"domestic_international",
        $"wholesaler",
        $"number_of_segments",
        $"subclass",
        $"adults__pax_",
        $"children__pax_",
        $"infants__pax_",
        $"total_segments_pax__exclude_infant_",
        $"collecting_entity",
        $"payment_scope",
        $"bank_names",
        $"installment_code",
        $"payment_fee_idr",
        $"mdr_installment_idr",
        $"coupon_code",
        $"gift_voucher_code",
        $"contract_currency",
        $"total_fare__contract_currency__idr",
        $"issuance_fee_idr",
        $"airline_reschedule_fee__contract_currency__idr",
        $"total_agent_fare__contract_currency__idr",
        $"traveloka_reschedule_fee__contract_currency__idr",
        $"unique_code__contract_currency__idr",
        $"base_fare_adult__per_pax__idr",
        $"base_fare_child__per_pax__idr",
        $"base_fare_infant__per_pax__idr",
        $"total_base_fare__exclude_infant__idr",
        $"new_gross_commission_idr",
        $"commission_tax_idr",
        $"net_commission_idr",
        $"nta_idr",
        $"bta_idr",
        $"commission_rule_id",
        $"commission_version",
        $"basic_incentive_idr",
        $"incentive_rule_id",
        $"incentive_rule_version",
        $"collecting_currency",
        $"invoice_amount_idr",
        $"total_fare__collecting_currency__idr",
        $"discount_premium_idr",
        $"total_agent_fare_idr",
        $"package_discount_premium_idr",
        $"unique_code_idr",
        $"coupon_value_idr",
        $"gift_voucher_value_idr",
        $"airline_reschedule_fee__collecting_currency__idr",
        $"traveloka_reschedule_fee_idr",
        $"installment_request_idr",
        $"transaction_fee_idr",
        $"point_redemption_idr",
        $"rebook_cost_idr",
        $"is_cross_selling_",
        $"reschedule_id",
        $"corporate_id",
        $"corporate_type",
        $"affiliate_id",
        $"commission_to_affiliate_idr",
        $"customer_country",
        $"vat_fee_idr",
        $"billing_amount_idr",
        $"seat_published_class",
        $"commission_to_collecting_entity_idr",
        $"non_connecting_discount_premium_idr",
        $"reschedule_mark_up_idr",
        $"is_credit_shell",
        $"commission_type",
        $"commission_adult_formula",
        $"commission_children__formula",
        $"commission_infant_formula",
        $"incentive_type",
        $"basic_incentive_adult_formula",
        $"basic_incentive_children_formula",
        $"basic_incentive_infant_formula",
        $"settlement_currency",
        $"billing_amount__settlement_currency__idr",
        $"total_fare__settlement_currency__idr",
        $"airline_reschedule_fee__settlement_currency__idr",
        $"traveloka_reschedule_fee__settlement_currency__idr",
        $"unique_code__settlement_currency__idr",
        $"base_fare_adult_per_pax__settlement_currency__idr",
        $"base_fare_child_per_pax__settlement_currency__idr",
        $"total_base_fare_exclude_infant__settlement_currency__idr",
        $"new_gross_commission__settlement_currency__idr",
        $"commission_tax__settlement_currency__idr",
        $"net_commission__settlement_currency__idr",
        $"basic_incentive__settlement_currency__idr",
        $"bta__settlement_currency__idr",
        $"issuance_fee__settlement_currency__idr",
        $"total_agent_fare__settlement_currency__idr",
        $"fare_basis",
        $"issuance_fare_source",
        $"discount_wht_idr",
        $"coupon_wht_idr",
        $"osi_code",
        $"redirection_partner",
        $"redirection_base_marketing_fee__collecting_currency_",
        $"flight_code",
        $"vat_out_idr",
        $"no_hold_booking_cost_idr",
        $"credit_shell_amount_idr",
        $"credit_shell_amount__settlement_currency_",
        $"base_fare_infant_per_pax__settlement_currency__idr",
        $"nta__settlement_currency__idr",
        $"business_partner_id",
        $"inventory_amount_idr",
        $"infant_fare_before_vat_idr",
        $"selling_entity",
        $"invoice_amount",
        $"mdr_charges",
        $"mdr_charges_idr"
      )
  }

  def get(): DataFrame = joinDataFrames
}